### ISSUE TITLE
STS에서 jsp 파일 오류

### ISSUE THREAD

**Issue by oognuyh** [acorngaru/konggaru#3]
## IDE
- [X] STS
- [ ] IntelliJ

## 내용
IntelliJ가 아닌 STS에서 *.jsp 파일을 열었을 때, backtick, li tag, i tag에서 오류가 발생합니다. 

## 스크린샷
![image](https://user-images.githubusercontent.com/48203569/120004587-ed1cd980-c011-11eb-8eff-8665007d4d24.png)
![image](https://user-images.githubusercontent.com/48203569/120005074-6fa59900-c012-11eb-80a3-0ccf6fe9bfb2.png)
![image](https://user-images.githubusercontent.com/48203569/120005464-d034d600-c012-11eb-9c63-4312ea279e28.png)

**Comment by nbbeom** [comment]
확인했습니다!

**Comment by oognuyh** [comment]
## 원인
서블릿 패키지가 포함되어있지 않기 때문에 발생

## 해결
1. 프로젝트의 컨텍스트 메뉴에서 Properties를 클릭
<img src="https://user-images.githubusercontent.com/48203569/120894718-e0713480-c654-11eb-9a6a-40e9ff4d40b1.png" width="300px" height="600px"/>  

2. Targeted Runtimes에서 현재 이클립스에 등록되어 있는 톰켓 서버 버전으로 변경
<img src="https://user-images.githubusercontent.com/48203569/120894726-e9fa9c80-c654-11eb-8756-d42ada4f29a1.png" width="300px" height="300px"/>

* 해당 부분까지만 진행해도 오류가 잡히지 않는 것을 확인했으나, 없어지지 않을 경우 아래 출처 확인

출처 - [Knowledge Repository](https://atoz-develop.tistory.com/entry/The-import-javaxservlet-cannot-be-resolved-%EC%97%90%EB%9F%AC-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95)
